"""empty message

Revision ID: 876ac3a0ba71
Revises: 072f7d40fe47
Create Date: 2019-07-14 19:48:40.087921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876ac3a0ba71'
down_revision = '072f7d40fe47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'create_time')
    # ### end Alembic commands ###
